services:
  app:
    image: veetavee/lineoa:${IMAGE_TAG:-latest}
    container_name: lineoa-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /home/worker/lineoa-dev/gcs-key.json:/app/config/gcs-key.json
    environment:
      - NODE_ENV=production
