services:
  app:
    image: veetavee/lineoa:${IMAGE_TAG:-latest}
    container_name: lineoa-app
    restart: unless-stopped
    ports:
      - "8080:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - /home/worker/lineoa-dev/media:/app/media
    networks:
      - db-network

networks:
  db-network:
    external: true
